### PR TITLE
Create A View switcher Component

### PR DESCRIPTION
**Pull request by jubalm**
The view switcher would be composed of a toggle and the visualizer.

Visual Example

| Screenshot 2024-06-26 at 1 41 59 PM | Screenshot 2024-06-26 at 1 43 01 PM |
|:--:|:--:|
|_raw view_|_parsed view_|

### CODE REVIEW

**Comment by KillariDev** [comment]
looks good

**Comment by KillariDev** [comment]
image
we probably need some kind of box around this? to make it look like one component

**Comment by KillariDev** [comment]
image

the box is missing from here. We could also add a button here to try to add the ABI, but that can be a separate PR

**Comment by jubalm** [comment]
> image
> the box is missing from here. We could also add a button here to try to add the ABI, but that can be a separate PR

No ABI message should now be same boxed design as parsed input on [21a4c32](https://github.com/DarkFlorist/TheInterceptor/pull/1055/commits/21a4c328fe6e82f498ee962210a32425a79d9adc)

Screenshot 2024-07-05 at 3 32 21 PM

**Review by KillariDev — APPROVED** [review]

**Pull request merged**
