### PR TITLE
Fix importance box overflow

### PR DESCRIPTION
**Pull request by KillariDev**
image

fixes https://github.com/DarkFlorist/TheInterceptor/issues/248

### CODE REVIEW

**Review by MicahZoltu — APPROVED** [review]

**Comment by MicahZoltu** [comment]
Why min-width?  It feels like we could allow the user to shrink as much as they want?

**Comment by KillariDev** [comment]
> Why min-width? It feels like we could allow the user to shrink as much as they want?

because I don't feel this looks nice
image

**Comment by KillariDev** [comment]
I guess ideally it should prefer that 400px size, but if it cannot make it, it would flex in different directions

**Comment by KillariDev** [comment]
I am not sure how to achieve that tho

**Comment by MicahZoltu** [comment]
If you want it to fill the container, then you should have it fill the container.  I agree with you that in your screenshot it shouldn't look like that, but I think min-width is the wrong solution.  Flexboxes/grids and whatnot are (though they are tricky to grok).

**Pull request merged**
