### PR TITLE
for arbitary EIP712 messages, add primary type to name as well

### PR DESCRIPTION
**Pull request by KillariDev**
To identify unsupported cases better (eg. https://github.com/DarkFlorist/TheInterceptor/issues/760)

image

### CODE REVIEW

**Review by jubalm — APPROVED** [review]

**Comment by KillariDev** [comment]
@coderabbitai review

**Comment by KillariDev** [comment]
@coderabbitai review

**Comment by KillariDev** [comment]
@coderabbit review

**Comment by KillariDev** [comment]
@coderabbitai review

**Pull request merged**
