### PR TITLE
Rename button fix and make tooltips more reliable

### PR DESCRIPTION
**Pull request by KillariDev**
Fixes https://github.com/DarkFlorist/TheInterceptor/issues/128

Also makes tooltips appear more reliably, and next to the curser instead of dependent on the object

### CODE REVIEW

**Review by MicahZoltu — APPROVED** [review]
It would be cool (but almost certainly not worth the time) if we had some kind of mock site that showcased a bunch of different features without needing to actually run/use the app.  Could serve it as a static site on each PR so the reviewer can easily poke around and look at the changes without downloading/installing the extension.

**Comment by KillariDev** [comment]
> It would be cool (but almost certainly not worth the time) if we had some kind of mock site that showcased a bunch of different features without needing to actually run/use the app. Could serve it as a static site on each PR so the reviewer can easily poke around and look at the changes without downloading/installing the extension.

yeah, we have that now for the absurd use and lunaria, but not for interceptor :/

**Comment by MicahZoltu** [comment]
The other two projects I think are notably easier because they are natively static hosted pages.  In the case of the extension, it would be cool if we can have a statically hosted version of some of the screens with some placeholder data mocked so PRs can easily be linked.  This is likely a lot of work.

**Comment by KillariDev** [comment]
> The other two projects I think are notably easier because they are natively static hosted pages. In the case of the extension, it would be cool if we can have a statically hosted version of some of the screens with some placeholder data mocked so PRs can easily be linked. This is likely a lot of work.

I added issue about this.

**Pull request merged**
